import { meta } from './meta'
import { en } from './en'
import { ru } from './ru'
import type { FrameworkData } from '../../_lib/post'

// This page's _data — meta (non-translatable) + en base + ru override. The page is
// the single source of truth; _components and the /framework catalog _list both read
// it (the catalog list is auto-generated by lib/parser-fs from this folder).
export const data: FrameworkData = { meta, en, overrides: { ru } }
