import { AUTHOR } from '@/lib/author'
import type { FrameworkMeta } from '../../_lib/post'

// Non-translatable fields for /framework/next-js. Standard co-located page: content
// lives in this folder's _data (en.ts + ru.ts), not generated by buildFrameworkData.
// order 1 keeps it second in the /framework catalog (after Fractera Pro).
export const meta: FrameworkMeta = {
  slug: 'next-js',
  subPath: '/framework/next-js',
  order: 1,
  tags: ['Next.js', 'SSR', 'App Router', 'Self-hosted', 'Agentic Engineering'],
  author: { name: AUTHOR.name, role: AUTHOR.role, url: AUTHOR.url },
  ogImage: '/Fractera-ai-workspace-screenshot.png',
}
