import { AUTHOR } from '@/lib/author'
import type { FrameworkMeta } from '../../_lib/post'

// Non-translatable fields for /framework/dotnet. Standard co-located page: content lives
// in this folder's _data (en.ts + ru.ts), not generated by buildFrameworkData.
export const meta: FrameworkMeta = {
  slug: 'dotnet',
  subPath: '/framework/dotnet',
  order: 33,
  tags: ['.NET', 'C#', 'Backend', 'Enterprise', 'Self-hosted', 'Agentic Engineering'],
  author: { name: AUTHOR.name, role: AUTHOR.role, url: AUTHOR.url },
  ogImage: '/Fractera-ai-workspace-screenshot.png',
}
