import { meta } from './meta'
import { en } from './en'
import { ru } from './ru'
import type { FrameworkData } from '../../_lib/post'

// This page's _data — meta + en base + ru override. Standard co-located singleton
// (CONTENT-I18N-ARCHITECTURE-STANDARD §7.6); no longer generated by buildFrameworkData.
export const data: FrameworkData = { meta, en, overrides: { ru } }
