import { AUTHOR } from '@/lib/author'
import type { FrameworkMeta } from '../../_lib/post'

// Non-translatable fields for /framework/react. Standard co-located page: content
// lives in this folder's _data (en.ts + ru.ts), not generated by buildFrameworkData.
// order 2 keeps it after Fractera Pro and Next.js in the /framework catalog.
export const meta: FrameworkMeta = {
  slug: 'react',
  subPath: '/framework/react',
  order: 2,
  tags: ['React', 'Vite', 'SPA', 'Self-hosted', 'Agentic Engineering'],
  author: { name: AUTHOR.name, role: AUTHOR.role, url: AUTHOR.url },
  ogImage: '/Fractera-ai-workspace-screenshot.png',
}
