import { AUTHOR } from '@/lib/author'
import type { FrameworkMeta } from '../../_lib/post'

// Non-translatable fields for /framework/vite. Standard co-located page: content lives
// in this folder's _data (en.ts + ru.ts), not generated by buildFrameworkData.
export const meta: FrameworkMeta = {
  slug: 'vite',
  subPath: '/framework/vite',
  order: 17,
  tags: ['Vite', 'Bundler', 'SPA', 'JavaScript', 'Self-hosted', 'Agentic Engineering'],
  author: { name: AUTHOR.name, role: AUTHOR.role, url: AUTHOR.url },
  ogImage: '/Fractera-ai-workspace-screenshot.png',
}
