import { meta } from './meta'
import { en } from './en'
import { ru } from './ru'
import type { FrameworkData } from '../../_lib/post'

// This page's _data — meta (non-translatable) + en base + ru override. Standard
// co-located singleton (CONTENT-I18N-ARCHITECTURE-STANDARD §7.6): the page IS the
// single source of truth. The /framework catalog _list and _components both read it.
// (No longer generated by the shared buildFrameworkData factory — fractera-pro is
// fully self-contained; the other frameworks still use the factory until refactored.)
export const data: FrameworkData = { meta, en, overrides: { ru } }
