import { AUTHOR } from '@/lib/author'
import type { FrameworkMeta } from '../../_lib/post'

// Non-translatable fields for /framework/fractera-pro. Standard co-located page: its
// content lives in this folder's _data (en.ts + ru.ts), not generated by the shared
// buildFrameworkData factory. order 0 keeps it first in the /framework catalog.
export const meta: FrameworkMeta = {
  slug: 'fractera-pro',
  subPath: '/framework/fractera-pro',
  order: 0,
  tags: ['Fractera Pro', 'Next.js', 'Parallel routing', 'Agentic Engineering'],
  author: { name: AUTHOR.name, role: AUTHOR.role, url: AUTHOR.url },
  ogImage: '/Fractera-ai-workspace-screenshot.png',
}
