import { AUTHOR } from '@/lib/author'
import type { FrameworkMeta } from '../../_lib/post'

// Non-translatable fields for /framework/remix. Standard co-located page: content lives
// in this folder's _data (en.ts + ru.ts), not generated by buildFrameworkData.
export const meta: FrameworkMeta = {
  slug: 'remix',
  subPath: '/framework/remix',
  order: 8,
  tags: ['Remix', 'React', 'SSR', 'Loaders', 'Self-hosted', 'Agentic Engineering'],
  author: { name: AUTHOR.name, role: AUTHOR.role, url: AUTHOR.url },
  ogImage: '/Fractera-ai-workspace-screenshot.png',
}
