import { Resend } from 'resend'
import { LEGAL, legalAddressOneLine } from '@/config/legal'

const resend = new Resend(process.env.RESEND_API_KEY)
const FROM = process.env.AUTH_RESEND_FROM ?? 'noreply@fractera.ai'

// CAN-SPAM Act (US) and analogous EU rules require a physical postal
// address in every commercial / transactional email. We append it
// automatically to whatever each template generated by wrapping the
// resend.emails.send() call — see sendEmail() below. Templates above
// continue to write their own HTML without thinking about the footer.
const CAN_SPAM_FOOTER_HTML = `
  <div style="margin-top:24px;padding-top:12px;border-top:1px solid #eee;font-size:11px;color:#999;line-height:1.5;font-family:sans-serif;text-align:center">
    ${legalAddressOneLine()}<br/>
    <a href="https://www.fractera.ai" style="color:#999;text-decoration:none">www.fractera.ai</a>
    &middot;
    <a href="mailto:${LEGAL.emails.support}" style="color:#999;text-decoration:none">${LEGAL.emails.support}</a>
  </div>
`

type SendArgs = Parameters<typeof resend.emails.send>[0]

async function sendEmail(args: SendArgs) {
  // Inject CAN-SPAM footer just before the LAST </div> in the HTML body.
  // If a template doesn't end in </div> (e.g. text-only or future plain),
  // append at the end. Either way, every outgoing email carries our
  // postal address + contact link.
  if (typeof args.html === 'string' && args.html.includes('</div>')) {
    const lastIdx = args.html.lastIndexOf('</div>')
    args = {
      ...args,
      html: args.html.slice(0, lastIdx) + CAN_SPAM_FOOTER_HTML + args.html.slice(lastIdx),
    }
  } else if (typeof args.html === 'string') {
    args = { ...args, html: args.html + CAN_SPAM_FOOTER_HTML }
  }
  return resend.emails.send(args)
}

const PIPELINE_SERVICES = [
  { name: 'Shell',  description: 'Your main application',       portHint: 'fractera-app' },
  { name: 'Auth',   description: 'Login & user management',     portHint: 'fractera-auth' },
  { name: 'Admin',  description: 'AI coding workspace',         portHint: 'fractera-admin' },
  { name: 'Bridge', description: 'AI platform terminals (×5)', portHint: 'fractera-bridge' },
  { name: 'Data',   description: 'File & media storage',        portHint: 'fractera-data' },
]

const AI_PLATFORMS = [
  'Claude Code',
  'Codex',
  'Gemini CLI',
  'Qwen Code',
  'Kimi Code',
]

function serviceListHtml(services: typeof PIPELINE_SERVICES) {
  return services
    .map(s => `<li style="margin:4px 0"><strong>${s.name}</strong> — ${s.description} <span style="color:#888;font-size:11px">(${s.portHint})</span></li>`)
    .join('\n')
}

export async function sendServerProvisionedEmail(to: string, ip: string, password: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Your Fractera server is created — IP and access details',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px">
        <h2 style="margin:0 0 12px">Your server is ready</h2>
        <p style="margin:0 0 16px">Your dedicated VPS has been created. Fractera is now being installed automatically — you'll receive a second email with your workspace URL when it's done (~15 min).</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Server credentials</p>
        <table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:24px">
          <tr><td style="padding:6px 0;color:#666;width:100px">IP address</td><td style="padding:6px 8px;font-weight:600">${ip}</td></tr>
          <tr><td style="padding:6px 0;color:#666">User</td><td style="padding:6px 8px;font-weight:600">root</td></tr>
          <tr><td style="padding:6px 0;color:#666">Password</td><td style="padding:6px 8px;font-weight:600;font-family:monospace">${password}</td></tr>
        </table>

        <p style="margin:0 0 8px;font-size:13px;color:#666">SSH access: <code style="background:#f4f4f4;padding:2px 6px;border-radius:3px">ssh root@${ip}</code></p>
        <p style="margin:0;font-size:12px;color:#999">You can use these credentials to upgrade your server plan directly on Contabo if needed.</p>
      </div>
    `,
  })
}

export async function sendWelcomeEmail(
  to: string,
  subdomain: string,
  credentials?: { ip: string; password: string }
) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Your Fractera server is ready',
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;padding:32px 24px;color:#0a0a0a">

        <!-- Hero -->
        <div style="text-align:center;padding-bottom:8px">
          <div style="display:inline-block;background:#10b981;color:#fff;font-size:11px;font-weight:600;letter-spacing:1.5px;text-transform:uppercase;padding:5px 12px;border-radius:20px;margin-bottom:14px">✓ Live</div>
          <h1 style="margin:0 0 8px;font-size:26px;font-weight:700;line-height:1.2">Your Fractera server is live</h1>
          <p style="margin:0;color:#666;font-size:15px;line-height:1.5">Open your workspace below to start coding with AI.</p>
        </div>

        <!-- Primary CTA -->
        <div style="text-align:center;margin:28px 0">
          <a href="https://admin.${subdomain}" style="display:inline-block;background:#6c47ff;color:#fff;font-weight:600;font-size:15px;text-decoration:none;padding:14px 28px;border-radius:10px">Open my workspace →</a>
          <p style="margin:10px 0 0;font-size:12px;color:#888;font-family:monospace">admin.${subdomain}</p>
        </div>

        <!-- The 3 main destinations -->
        <table role="presentation" style="width:100%;border-collapse:separate;border-spacing:0 8px;margin:24px 0 0">
          <tr>
            <td style="background:#fafafa;border:1px solid #eee;border-radius:10px;padding:14px 16px">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:2px">Live app</div>
              <a href="https://${subdomain}" style="color:#6c47ff;font-weight:600;font-size:14px;text-decoration:none">https://${subdomain}</a>
              <div style="font-size:12px;color:#888;margin-top:4px">The site you publish for your end users.</div>
            </td>
          </tr>
          <tr>
            <td style="background:#fafafa;border:1px solid #eee;border-radius:10px;padding:14px 16px">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:2px">Hermes — your AI orchestrator</div>
              <a href="https://hermes.${subdomain}" style="color:#6c47ff;font-weight:600;font-size:14px;text-decoration:none">hermes.${subdomain}</a>
              <div style="font-size:12px;color:#888;margin-top:4px">Speak to Hermes from Telegram or chat. It delegates work to the right AI for each step.</div>
            </td>
          </tr>
          <tr>
            <td style="background:#fafafa;border:1px solid #eee;border-radius:10px;padding:14px 16px">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:2px">Company Brain</div>
              <a href="https://lightrag.${subdomain}/" style="color:#6c47ff;font-weight:600;font-size:14px;text-decoration:none">Open in workspace</a>
              <div style="font-size:12px;color:#888;margin-top:4px">Your private knowledge base. Feed it docs, query it from any AI tool on the workspace.</div>
            </td>
          </tr>
        </table>

        <!-- Account note -->
        <div style="margin:24px 0 8px;padding:12px 14px;background:#f5f3ff;border-left:3px solid #6c47ff;border-radius:4px">
          <div style="font-size:13px;color:#444;line-height:1.5">
            Manage all your servers at <a href="https://www.fractera.ai/dashboard" style="color:#6c47ff;font-weight:600;text-decoration:none">fractera.ai/dashboard</a> — sign in with <strong>${to}</strong>.
          </div>
        </div>

        ${credentials ? `
        <!-- SSH — collapsed-looking, deprioritized -->
        <div style="margin-top:32px;padding-top:20px;border-top:1px solid #eee">
          <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:8px">Server access (advanced)</div>
          <p style="margin:0 0 10px;font-size:12px;color:#666;line-height:1.5">For terminal access to the underlying VPS — install extra software, integrate third-party services, etc. Treat this like a password to your computer.</p>
          <table style="width:100%;border-collapse:collapse;font-size:13px;background:#fafafa;border:1px solid #eee;border-radius:8px;padding:0">
            <tr><td style="padding:8px 12px;color:#888;width:80px;border-bottom:1px solid #f0f0f0">IP</td><td style="padding:8px 12px;font-family:monospace;border-bottom:1px solid #f0f0f0">${credentials.ip}</td></tr>
            <tr><td style="padding:8px 12px;color:#888;border-bottom:1px solid #f0f0f0">User</td><td style="padding:8px 12px;font-family:monospace;border-bottom:1px solid #f0f0f0">root</td></tr>
            <tr><td style="padding:8px 12px;color:#888">Password</td><td style="padding:8px 12px;font-family:monospace">${credentials.password}</td></tr>
          </table>
        </div>
        ` : ''}

        <!-- AI platforms — minor footnote -->
        <p style="margin:24px 0 0;font-size:11px;color:#aaa;text-align:center;line-height:1.6">
          Powered by ${AI_PLATFORMS.join(' · ')}
        </p>

      </div>
    `,
  })
}

export async function sendExpiryWarningEmail(to: string, daysLeft: number, subdomain: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: `Your Fractera subscription expires in ${daysLeft} days`,
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px">
        <h2 style="margin:0 0 12px">Subscription expiring soon</h2>
        <p style="margin:0 0 16px">Your Fractera server <strong>${subdomain}</strong> subscription expires in <strong>${daysLeft} day${daysLeft === 1 ? '' : 's'}</strong>.</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Services at risk (5 pipeline services)</p>
        <ul style="margin:0 0 16px;padding-left:20px;line-height:1.8">
          ${serviceListHtml(PIPELINE_SERVICES)}
        </ul>

        <p style="margin:0 0 16px">To keep all services running, please renew your subscription before the expiry date.</p>
        <p><a href="https://fractera.ai">Manage subscription →</a></p>
      </div>
    `,
  })
}


export async function sendQueuedEmail(to: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Fractera — your workspace is being prepared',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px">
        <h2 style="margin:0 0 12px">Purchase confirmed</h2>
        <p style="margin:0 0 16px">Thank you! Your Fractera workspace is being prepared. You will receive a second email with your server IP, login, and password within <strong>60 minutes</strong>.</p>
        <p style="margin:0;font-size:12px;color:#999">If you have any questions, reply to this email.</p>
      </div>
    `,
  })
}

export async function sendAdminAlertEmail(userEmail: string, subscriptionId: string) {
  const adminUrl = process.env.AUTH_URL ?? process.env.NEXTAUTH_URL ?? 'https://fractera.ai'
  await sendEmail({
    from: FROM,
    to: 'admin@fractera.ai',
    subject: '🚨 Fractera — user purchased with empty pool',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px">
        <h2 style="margin:0 0 12px;color:#e53e3e">Action required: no servers in pool</h2>
        <p style="margin:0 0 16px">A user completed payment but no server was available in the reserve pool.</p>
        <table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:24px">
          <tr><td style="padding:6px 0;color:#666;width:140px">User email</td><td style="padding:6px 8px;font-weight:600">${userEmail}</td></tr>
          <tr><td style="padding:6px 0;color:#666">Subscription ID</td><td style="padding:6px 8px;font-family:monospace;font-size:12px">${subscriptionId}</td></tr>
        </table>
        <p style="margin:0 0 16px">Add a server to the pool and assign it to this user:</p>
        <a href="${adminUrl}/admin" style="display:inline-block;background:#fff;color:#000;padding:10px 20px;border-radius:8px;text-decoration:none;font-weight:600">Open Admin Panel →</a>
      </div>
    `,
  })
}


export async function sendInstallStartedEmail(to: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Your Fractera installation has started',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px;color:#111">
        <h2 style="margin:0 0 8px;font-size:22px;font-weight:700">Installation started</h2>
        <p style="margin:0 0 20px;color:#444;line-height:1.6">
          We're setting up Fractera on your server right now.
          This usually takes <strong>15–20 minutes</strong>.
        </p>

        <p style="margin:0 0 6px;font-size:11px;color:#999;text-transform:uppercase;letter-spacing:1px">What happens next</p>
        <ol style="margin:0 0 20px;padding-left:20px;color:#444;line-height:2">
          <li>You'll receive a short update when dependencies are installed</li>
          <li>The final email will contain your workspace URLs and SSH credentials</li>
        </ol>

        <div style="background:#f7f7f7;border-radius:8px;padding:16px;margin-bottom:20px">
          <p style="margin:0 0 8px;font-size:13px;font-weight:600;color:#333">You can also check status anytime</p>
          <p style="margin:0;font-size:13px;color:#555;line-height:1.6">
            Visit <a href="https://fractera.ai" style="color:#6c47ff">fractera.ai</a>, sign in, and open the
            <strong>Servers</strong> tab — your domain will appear there once installation is complete.
          </p>
        </div>

        <p style="margin:0;font-size:12px;color:#888;line-height:1.6">
          If you re-enter your server IP and password on fractera.ai, the dashboard will detect the current state
          and offer options like removing Fractera branding or deleting the server.
        </p>
      </div>
    `,
  })
}

export async function sendLightInstallStartedEmail(to: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Fractera Light — your backend is being installed',
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:520px;margin:0 auto;padding:32px 24px;color:#111">
        <h2 style="margin:0 0 8px;font-size:22px;font-weight:700">Installation started</h2>
        <p style="margin:0 0 20px;color:#444;line-height:1.6">
          We're setting up <strong>Fractera Light</strong> on your server.
          This usually takes <strong>10–12 minutes</strong>.
        </p>

        <p style="margin:0 0 6px;font-size:11px;color:#999;text-transform:uppercase;letter-spacing:1px">What's being installed</p>
        <ul style="margin:0 0 20px;padding-left:20px;color:#444;line-height:2;font-size:14px">
          <li><strong>App</strong> — your landing page + protected dashboard</li>
          <li><strong>Auth</strong> — login, registration, roles, guest access</li>
          <li><strong>Data</strong> — file & media storage (SQLite + local storage)</li>
        </ul>

        <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:10px;padding:16px;margin-bottom:20px">
          <p style="margin:0 0 6px;font-size:13px;font-weight:600;color:#166534">When it's done you'll get</p>
          <ul style="margin:0;padding-left:18px;color:#166534;font-size:13px;line-height:1.8">
            <li>Your public site URL</li>
            <li>Admin panel URL — sign in to manage your site</li>
            <li>Cloudflare HTTPS on both</li>
          </ul>
        </div>

        <p style="margin:0;font-size:12px;color:#888;line-height:1.6">
          You can watch live progress at
          <a href="https://fractera.ai/light" style="color:#0ea5e9">fractera.ai/light</a>
          — the install bar on the page updates in real time.
        </p>
      </div>
    `,
  })
}

export async function sendLightWelcomeEmail(to: string, subdomain: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Your Fractera Light backend is live',
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;padding:32px 24px;color:#0a0a0a">

        <div style="text-align:center;padding-bottom:8px">
          <div style="display:inline-block;background:#10b981;color:#fff;font-size:11px;font-weight:600;letter-spacing:1.5px;text-transform:uppercase;padding:5px 12px;border-radius:20px;margin-bottom:14px">✓ Live</div>
          <h1 style="margin:0 0 8px;font-size:26px;font-weight:700;line-height:1.2">Your Fractera Light backend is live</h1>
          <p style="margin:0;color:#666;font-size:15px;line-height:1.5">Sign in to the admin panel to manage your site.</p>
        </div>

        <div style="text-align:center;margin:28px 0">
          <a href="https://${subdomain}/admin" style="display:inline-block;background:#0ea5e9;color:#fff;font-weight:600;font-size:15px;text-decoration:none;padding:14px 28px;border-radius:10px">Open admin panel →</a>
          <p style="margin:10px 0 0;font-size:12px;color:#888;font-family:monospace">${subdomain}/admin</p>
        </div>

        <table role="presentation" style="width:100%;border-collapse:separate;border-spacing:0 8px;margin:24px 0 0">
          <tr>
            <td style="background:#fafafa;border:1px solid #eee;border-radius:10px;padding:14px 16px">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:2px">Your public site</div>
              <a href="https://${subdomain}" style="color:#0ea5e9;font-weight:600;font-size:14px;text-decoration:none">https://${subdomain}</a>
              <div style="font-size:12px;color:#888;margin-top:4px">Landing page visible to your visitors.</div>
            </td>
          </tr>
          <tr>
            <td style="background:#fafafa;border:1px solid #eee;border-radius:10px;padding:14px 16px">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:2px">Admin panel</div>
              <a href="https://${subdomain}/admin" style="color:#0ea5e9;font-weight:600;font-size:14px;text-decoration:none">https://${subdomain}/admin</a>
              <div style="font-size:12px;color:#888;margin-top:4px">Create your admin account on first visit. Role-based access is pre-configured.</div>
            </td>
          </tr>
        </table>

        <div style="margin:24px 0 8px;padding:12px 14px;background:#f0f9ff;border-left:3px solid #0ea5e9;border-radius:4px">
          <div style="font-size:13px;color:#444;line-height:1.5">
            Git sync is built in — use the pull / push buttons in the admin panel to sync your code with the server.
          </div>
        </div>

        <div style="margin:32px 0 0;padding:24px 20px;background:linear-gradient(135deg,#fef9c3 0%,#fef3c7 100%);border:1px solid #fcd34d;border-radius:14px;text-align:center">
          <p style="margin:0 0 4px;font-size:11px;color:#92400e;text-transform:uppercase;letter-spacing:1.5px;font-weight:700">Support Fractera</p>
          <h3 style="margin:0 0 10px;font-size:18px;font-weight:700;color:#78350f">Liked the result? Become a sponsor</h3>
          <p style="margin:0 0 16px;color:#92400e;font-size:13px;line-height:1.6">
            Deploying projects like yours is not free for us. Fractera exists thanks to people like you.
            If you can spare <strong>$1/month</strong>, you will make a real difference for our project.
          </p>
          <a href="https://www.fractera.ai/en#sponsors" style="display:inline-block;background:#d97706;color:#fff;font-weight:600;font-size:14px;text-decoration:none;padding:12px 24px;border-radius:10px">Become a sponsor →</a>
        </div>

        <div style="margin:20px 0 0;border-top:1px solid #e5e7eb;padding-top:20px;text-align:center">
          <p style="margin:0 0 4px;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:1px;font-weight:600">— or —</p>
          <p style="margin:0 0 12px;color:#374151;font-size:13px;line-height:1.6">
            We really value your attention. If you find Fractera useful,
            please give us a star on GitHub — it helps more people discover the project.
          </p>
          <a href="https://github.com/Fractera/ai-workspace" style="display:inline-block;background:#24292f;color:#fff;font-weight:600;font-size:14px;text-decoration:none;padding:10px 22px;border-radius:10px">Star on GitHub ★</a>
        </div>

      </div>
    `,
  })
}

export async function sendInstallProgressEmail(to: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Fractera: dependencies installed — building services',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px;color:#111">
        <h2 style="margin:0 0 8px;font-size:22px;font-weight:700">Good progress</h2>
        <p style="margin:0 0 20px;color:#444;line-height:1.6">
          All dependencies have been installed on your server.
          We're now building the Fractera services and configuring your domain.
        </p>
        <p style="margin:0 0 20px;color:#444;line-height:1.6">
          You'll receive the final email with your workspace URLs in <strong>5–10 more minutes</strong>.
        </p>
        <p style="margin:0;font-size:12px;color:#888">
          Check status anytime at <a href="https://fractera.ai" style="color:#6c47ff">fractera.ai</a> → Servers tab.
        </p>
      </div>
    `,
  })
}

export async function sendSponsorThankYouEmail(to: string, tier: 's1' | 's5' | 's20') {
  const tierLabel = tier === 's1' ? '$1/month' : tier === 's5' ? '$5/month' : '$20/month'
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Thank you for sponsoring Fractera 💛',
    html: `
      <div style="font-family:sans-serif;max-width:560px;margin:0 auto;padding:32px 24px;color:#111">
        <div style="text-align:center;font-size:56px;line-height:1;margin-bottom:16px">💛</div>
        <h1 style="margin:0 0 16px;font-size:26px;font-weight:700;text-align:center;color:#111">
          Thank you for becoming a sponsor!
        </h1>

        <p style="margin:0 0 20px;color:#333;line-height:1.7;font-size:16px;text-align:center">
          Your <strong>${tierLabel}</strong> support means the world to me — Fractera is built by one person, and every sponsor is a real boost.
        </p>

        <div style="background:linear-gradient(135deg,#fef9c3 0%,#fef3c7 100%);border:1px solid #fcd34d;border-radius:14px;padding:20px;margin:24px 0">
          <p style="margin:0 0 8px;font-size:11px;color:#92400e;text-transform:uppercase;letter-spacing:1.5px;font-weight:700">What happens next</p>
          <ul style="margin:0;padding-left:18px;color:#1f2937;line-height:1.8;font-size:14px">
            <li>Your email will be listed on the <strong>Sponsors</strong> page here on fractera.ai</li>
            <li>You'll be added to the public Sponsors section in our GitHub repository</li>
            <li>You can manage or cancel your subscription anytime from the Dashboard</li>
          </ul>
        </div>

        <div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:14px;padding:20px;margin:24px 0;text-align:center">
          <p style="margin:0 0 8px;font-size:11px;color:#1e40af;text-transform:uppercase;letter-spacing:1.5px;font-weight:700">Join the private Telegram group</p>
          <p style="margin:0 0 14px;color:#1e3a8a;line-height:1.6;font-size:14px">
            A closed group for Fractera sponsors — roadmap previews, early features, and direct chat with the team.
          </p>
          <a href="https://t.me/+7TABWdWliKBiYmI8" style="display:inline-block;background:#2563eb;color:#fff;padding:10px 22px;border-radius:10px;text-decoration:none;font-weight:600;font-size:14px">
            Join Telegram →
          </a>
        </div>

        <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:14px;padding:20px;margin:24px 0">
          <p style="margin:0 0 8px;font-size:11px;color:#374151;text-transform:uppercase;letter-spacing:1.5px;font-weight:700">We're in touch</p>
          <p style="margin:0;color:#374151;line-height:1.7;font-size:14px">
            If you have ideas, feature requests, or wishes for the project —
            <strong>just reply to this email</strong>. Your message lands directly with me, and I read every one personally.
          </p>
        </div>

        <p style="margin:32px 0 0;color:#6b7280;line-height:1.6;font-size:13px;text-align:center">
          With sincere gratitude,<br>
          <strong style="color:#111">The Fractera team</strong>
        </p>
      </div>
    `,
  })
}

export async function sendCancellationEmail(to: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Fractera subscription cancelled',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px">
        <h2 style="margin:0 0 12px">Subscription cancelled</h2>
        <p style="margin:0 0 16px">Your Fractera subscription has been cancelled. The following pipeline services will be deactivated at the end of the current billing period:</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Services being deactivated (5 pipeline services)</p>
        <ul style="margin:0 0 16px;padding-left:20px;line-height:1.8">
          ${serviceListHtml(PIPELINE_SERVICES)}
        </ul>

        <p style="margin:0 0 16px">If this was a mistake, you can resubscribe at any time from <a href="https://fractera.ai">fractera.ai</a>.</p>
      </div>
    `,
  })
}

export async function sendPartnerWelcomeEmail(to: string, slug: string) {
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Your Fractera Partner cabinet is active',
    html: `
      <div style="font-family:sans-serif;max-width:560px;margin:0 auto;padding:32px 24px;color:#111">
        <h1 style="margin:0 0 16px;font-size:24px;font-weight:700;color:#111">
          Welcome to the Fractera Partner Program
        </h1>

        <p style="margin:0 0 20px;color:#333;line-height:1.7;font-size:15px">
          Your partner cabinet is now active. Below is your personal partner identifier — keep it safe; you will use it when configuring your affiliate links and (later) when configuring the embeddable widget and MCP activation.
        </p>

        <div style="background:linear-gradient(135deg,#f3f0ff 0%,#ede4ff 100%);border:1px solid #c4b5fd;border-radius:14px;padding:20px;margin:24px 0">
          <p style="margin:0 0 8px;font-size:11px;color:#6d28d9;text-transform:uppercase;letter-spacing:1.5px;font-weight:700">Your partner ID</p>
          <p style="margin:0;font-family:monospace;font-size:20px;font-weight:700;color:#1f2937;letter-spacing:0.5px">${slug}</p>
        </div>

        <h2 style="margin:24px 0 12px;font-size:18px;font-weight:700;color:#111">Widget snippet</h2>
        <p style="margin:0 0 16px;color:#333;line-height:1.7;font-size:14px">
          The embeddable signup widget is under active development. Once it ships, you will be able to copy a ready-to-paste snippet from your partner cabinet at <a href="https://fractera.ai" style="color:#6c47ff;font-weight:600">fractera.ai</a> → Dashboard → Partner cabinet. The snippet will look approximately like this:
        </p>

        <pre style="background:#0b0b0d;color:#a7f3d0;font-family:monospace;font-size:12px;border-radius:10px;padding:16px;overflow:auto;line-height:1.5;margin:0 0 16px"><code>&lt;iframe
  src="https://embed.fractera.ai/signup?ref=${slug}"
  width="100%" height="640"
  style="border:0; border-radius:16px"
&gt;&lt;/iframe&gt;</code></pre>

        <p style="margin:0 0 24px;color:#666;line-height:1.6;font-size:13px">
          The widget will surface a call-to-action button labelled with your hosting provider name and linking to your affiliate URL — both you configure in the cabinet once it ships.
        </p>

        <h2 style="margin:24px 0 12px;font-size:18px;font-weight:700;color:#111">What to do next</h2>
        <ul style="margin:0 0 16px;padding-left:20px;line-height:1.8;color:#1f2937;font-size:14px">
          <li>Open <a href="https://fractera.ai" style="color:#6c47ff;font-weight:600">fractera.ai</a> → Dashboard (top-right corner of the page after signing in) → tab <strong>«Partner cabinet»</strong>.</li>
          <li>Apply for an affiliate program with any VPS provider you want to recommend (Contabo's program is documented at <a href="https://contabo.com/en/affiliate-program/" style="color:#6c47ff;font-weight:600">contabo.com/en/affiliate-program/</a> — but any host with an affiliate program works).</li>
          <li>Once approved by the provider, connect your affiliate link in the cabinet — that will happen as soon as link management ships (next development step).</li>
        </ul>

        <p style="margin:24px 0 0;color:#666;font-size:13px;line-height:1.6">
          Questions? Reply directly to this email — it goes to admin@fractera.ai.
        </p>
      </div>
    `,
  })
}

// Sent right after a ServerToken is created — by ANY deploy path (main /api/install,
// embed /api/embed/install, or MCP register_and_deploy). The install-started email
// is sent BEFORE the ServerToken row exists, so it cannot carry the recovery token —
// this follow-up closes that gap. The token unlocks MCP retry_deploy if anything
// breaks later. Best-effort: callers wrap in try/catch and never fail the deploy
// because of an email send error.
export async function sendRecoveryTokenEmail(to: string, serverToken: string) {
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Save your Fractera recovery token (backup — only if needed)',
    html: `
      <div style="font-family:sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#111">
        <h2 style="margin:0 0 12px">Save this in case anything goes wrong</h2>

        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          We just launched the deployment of your Fractera server. The next
          email you receive will either contain your live URL (most likely) or
          a failure report. <strong>You do not need to do anything right now.</strong>
        </p>

        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          This message is a backup. If the deploy ever gets stuck, fails, or
          you want to re-run it later, the token below lets any AI agent
          (Claude, ChatGPT/Codex, Gemini) recover the same server for you.
        </p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Your recovery token</p>
        <p style="margin:0 0 20px;font-size:13px;color:#1f2937;font-family:monospace;background:#f5f3ff;border:1px solid #ddd6fe;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all;user-select:all">${escapeHtml(serverToken)}</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Fractera MCP server URL</p>
        <p style="margin:0 0 20px;font-size:13px;color:#1f2937;font-family:monospace;background:#f5f3ff;border:1px solid #ddd6fe;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all;user-select:all">https://www.fractera.ai/api/mcp</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">How to use it (only if you need to)</p>
        <ol style="margin:0 0 20px;padding-left:20px;line-height:1.7;color:#1f2937;font-size:14px">
          <li style="margin-bottom:8px">
            Open the AI agent you use day-to-day — Claude, ChatGPT/Codex, or
            Gemini. Some agents call this an &ldquo;MCP server&rdquo;, others
            call it a &ldquo;connector&rdquo; — same thing.
          </li>
          <li style="margin-bottom:8px">
            Tell the agent in plain language: <em>&ldquo;Please connect the
            MCP server at https://www.fractera.ai/api/mcp. Once connected, retry
            my Fractera deploy with this recovery token: ${escapeHtml(serverToken.slice(0, 12))}&hellip;&rdquo;</em>
            The agent will walk you through the 15-second connector
            setup inside its own interface, then call our <code>retry_deploy</code>
            tool with your token.
          </li>
          <li style="margin-bottom:8px">
            That&rsquo;s it. The agent will wipe the partial install and run a
            fresh deploy on the same server. You&rsquo;ll receive a new welcome
            email when it&rsquo;s done.
          </li>
        </ol>

        <p style="margin:0 0 16px;color:#555;font-size:13px;line-height:1.6;background:#fffbeb;border:1px solid #fef3c7;border-radius:8px;padding:12px">
          <strong style="color:#92400e">If everything goes well — you can safely
          ignore this email.</strong> Most deploys complete on the first try.
          We send this as a one-time safety net because the recovery token is
          generated by the deploy itself and is not available in the
          install-started email.
        </p>

        <p style="margin:0 0 16px;color:#777;font-size:12px;line-height:1.6">
          Treat the recovery token like a password — anyone who has it can
          re-run a deploy on this same server using your stored IP and
          credentials. Do not share it publicly.
        </p>

        <p style="margin:0;color:#666;font-size:13px;line-height:1.6">
          Questions? Reply directly to this email — it goes to admin@fractera.ai.
        </p>
      </div>
    `,
  })
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] ?? c))
}

type BlackBoxInquiry = {
  email: string
  name?: string
  company?: string
  area?: string
  country?: string
  companyDoes?: string
  aiTask?: string
  telegram?: string
  lang?: string
}

export async function sendBlackBoxInquiryEmail(inquiry: BlackBoxInquiry) {
  const rows: [string, string | undefined][] = [
    ['Email', inquiry.email],
    ['Name', inquiry.name],
    ['Company', inquiry.company],
    ['Area of activity', inquiry.area],
    ['Country', inquiry.country],
    ['What the company does', inquiry.companyDoes],
    ['AI task they want to solve', inquiry.aiTask],
    ['Telegram', inquiry.telegram],
    ['UI language at submission', inquiry.lang],
  ]
  const rowsHtml = rows
    .filter(([, v]) => v && v.trim())
    .map(([label, v]) => `
      <tr>
        <td style="padding:8px 12px;font-size:12px;color:#666;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #eee;vertical-align:top;white-space:nowrap">${escapeHtml(label)}</td>
        <td style="padding:8px 12px;font-size:14px;color:#111;border-bottom:1px solid #eee;white-space:pre-wrap;line-height:1.5">${escapeHtml((v ?? '').trim())}</td>
      </tr>
    `).join('\n')

  await sendEmail({
    from: FROM,
    to: 'admin@fractera.ai',
    replyTo: inquiry.email,
    subject: `Black Box inquiry — ${inquiry.company?.trim() || inquiry.email}`,
    html: `
      <div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#111">
        <h2 style="margin:0 0 6px">Fractera Black Box — new consultation inquiry</h2>
        <p style="margin:0 0 16px;color:#666;font-size:13px">Reply directly to this email — it goes to the inquirer (${escapeHtml(inquiry.email)}).</p>
        <table style="width:100%;border-collapse:collapse;border:1px solid #eee">
          ${rowsHtml}
        </table>
      </div>
    `,
  })
}

export async function sendDeployFailedEmail(to: string, errorMessage?: string, serverToken?: string) {
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Your Fractera deployment did not complete',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px;color:#111">
        <h2 style="margin:0 0 12px">Deployment did not complete</h2>
        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          We started setting up your Fractera server, but the deployment ran
          into a problem and could not finish. Your server is <strong>not
          ready</strong> — the URL we mentioned in the previous email will not
          work.
        </p>

        ${errorMessage ? `
        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">What went wrong</p>
        <p style="margin:0 0 20px;font-size:13px;color:#b91c1c;font-family:monospace;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:12px;line-height:1.5;word-break:break-word">${errorMessage}</p>
        ` : ''}

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">How to recover</p>
        <ol style="margin:0 0 20px;padding-left:20px;line-height:1.8;color:#1f2937;font-size:14px">
          <li>
            Open your dashboard at
            <a href="https://fractera.ai" style="color:#6c47ff;font-weight:600">fractera.ai</a>
            (sign in with <strong>${to}</strong>) &rarr; <strong>Servers</strong>,
            delete the failed deployment, and start a new one from the home page.
          </li>
          <li>
            Or use the <strong>MCP-assisted recovery</strong>: paste the
            server_token below into an AI agent that has the
            <a href="https://fractera.ai/en/partners#mcp" style="color:#6c47ff;font-weight:600">Fractera MCP</a>
            enabled (Claude Code, Codex, Gemini CLI). The agent will call
            <code>retry_deploy</code> and finish the setup of the server you
            already started.
            <br/>
            <span style="display:inline-block;margin-top:6px;color:#d97706;font-size:12px">
              * Never used MCP? Copy this URL and ask your AI agent to connect it: <strong>https://www.fractera.ai/api/mcp</strong> — setup takes ~15 seconds.
            </span>
          </li>
        </ol>

        ${serverToken ? `
        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Your server_token</p>
        <p style="margin:0 0 20px;font-size:13px;color:#1f2937;font-family:monospace;background:#f5f3ff;border:1px solid #ddd6fe;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all;user-select:all">${serverToken}</p>
        ` : ''}

        <p style="margin:0;color:#666;font-size:13px;line-height:1.6">
          Need help? Reply directly to this email — it goes to admin@fractera.ai.
        </p>
      </div>
    `,
  })
}

export async function sendLightRecoveryTokenEmail(to: string, serverToken: string) {
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Save your Fractera Light recovery token (backup — only if needed)',
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#0a0a0a">
        <h2 style="margin:0 0 12px;font-size:22px;font-weight:700">Save this in case anything goes wrong</h2>

        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          We just launched the deployment of your Fractera Light backend. The
          next email you receive will either contain your live URL (most likely)
          or a failure report. <strong>You do not need to do anything right now.</strong>
        </p>

        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          This message is a backup. If the deploy ever gets stuck, fails, or
          you want to re-run it later, the token below lets any AI agent
          (Claude, ChatGPT/Codex, Gemini) recover the same server for you.
        </p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Your recovery token</p>
        <p style="margin:0 0 20px;font-size:13px;color:#0a0a0a;font-family:monospace;background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all;user-select:all">${escapeHtml(serverToken)}</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Fractera Light MCP server URL</p>
        <p style="margin:0 0 20px;font-size:13px;color:#0a0a0a;font-family:monospace;background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all;user-select:all">https://www.fractera.ai/api/mcp/light</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">How to use it (only if you need to)</p>
        <ol style="margin:0 0 20px;padding-left:20px;line-height:1.7;color:#1f2937;font-size:14px">
          <li style="margin-bottom:8px">
            Open the AI agent you use day-to-day — Claude, ChatGPT/Codex, or
            Gemini. Some agents call this an &ldquo;MCP server&rdquo;, others
            call it a &ldquo;connector&rdquo; — same thing.
          </li>
          <li style="margin-bottom:8px">
            Tell the agent in plain language: <em>&ldquo;Please connect the
            MCP server at https://www.fractera.ai/api/mcp/light. Once connected,
            retry my Fractera Light deploy with this recovery token:
            ${escapeHtml(serverToken.slice(0, 12))}&hellip;&rdquo;</em>
            The agent will walk you through the 15-second connector setup
            inside its own interface, then call our <code>retry_deploy</code>
            tool with your token.
          </li>
          <li style="margin-bottom:8px">
            That&rsquo;s it. The agent will wipe the partial install and run a
            fresh Light deploy on the same server. You&rsquo;ll receive a new
            welcome email when it&rsquo;s done.
          </li>
        </ol>

        <p style="margin:0 0 16px;color:#555;font-size:13px;line-height:1.6;background:#fffbeb;border:1px solid #fef3c7;border-radius:8px;padding:12px">
          <strong style="color:#92400e">If everything goes well — you can safely
          ignore this email.</strong> Most deploys complete on the first try.
          We send this as a one-time safety net because the recovery token is
          generated by the deploy itself and is not available in the
          install-started email.
        </p>

        <p style="margin:0 0 16px;color:#777;font-size:12px;line-height:1.6">
          Treat the recovery token like a password — anyone who has it can
          re-run a deploy on this same server using your stored IP and
          credentials. Do not share it publicly.
        </p>

        <p style="margin:0;color:#666;font-size:13px;line-height:1.6">
          Questions? Reply directly to this email — it goes to admin@fractera.ai.
        </p>
      </div>
    `,
  })
}

export async function sendLightDeployFailedEmail(to: string, errorMessage?: string, serverToken?: string) {
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Your Fractera Light deployment did not complete',
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:520px;margin:0 auto;padding:24px;color:#0a0a0a">
        <h2 style="margin:0 0 12px;font-size:22px;font-weight:700">Deployment did not complete</h2>
        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          We started setting up your Fractera Light backend, but the deployment
          ran into a problem and could not finish. Your server is <strong>not
          ready</strong> — the URL we mentioned in the previous email will not
          work.
        </p>

        ${errorMessage ? `
        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">What went wrong</p>
        <p style="margin:0 0 20px;font-size:13px;color:#b91c1c;font-family:monospace;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:12px;line-height:1.5;word-break:break-word">${escapeHtml(errorMessage)}</p>
        ` : ''}

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">How to recover</p>
        <ol style="margin:0 0 20px;padding-left:20px;line-height:1.8;color:#1f2937;font-size:14px">
          <li>
            Open your dashboard at
            <a href="https://fractera.ai" style="color:#0ea5e9;font-weight:600">fractera.ai</a>
            (sign in with <strong>${escapeHtml(to)}</strong>) &rarr; <strong>Servers</strong>,
            delete the failed deployment, and start a new one from the Light page.
          </li>
          <li>
            Or use the <strong>MCP-assisted recovery</strong>: paste the
            server_token below into an AI agent that has the
            <strong>Fractera Light MCP</strong> enabled (Claude Code, Codex,
            Gemini CLI). The agent will call <code>retry_deploy</code> and
            finish the setup of the server you already started.
            <br/>
            <span style="display:inline-block;margin-top:6px;color:#0369a1;font-size:12px">
              * Never used MCP? Copy this URL and ask your AI agent to connect it: <strong>https://www.fractera.ai/api/mcp/light</strong> — setup takes ~15 seconds.
            </span>
          </li>
        </ol>

        ${serverToken ? `
        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Your server_token</p>
        <p style="margin:0 0 20px;font-size:13px;color:#0a0a0a;font-family:monospace;background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all;user-select:all">${escapeHtml(serverToken)}</p>
        ` : ''}

        <p style="margin:0;color:#666;font-size:13px;line-height:1.6">
          Need help? Reply directly to this email — it goes to admin@fractera.ai.
        </p>
      </div>
    `,
  })
}

type DnsQuotaInfo = {
  current: number
  limit: number
  planTier: string
  nextTier?: { name: string; limit: number; monthly: string }
}

// Sent to admin when DNS records in the Cloudflare zone cross the warning
// threshold (~80%). Bootstrap continues; this is a heads-up so the operator
// has time to upgrade the plan or run a cleanup BEFORE deploys start to fail.
export async function sendDnsQuotaWarningEmail(to: string, info: DnsQuotaInfo) {
  const pct = Math.round((info.current / info.limit) * 100)
  const remaining = info.limit - info.current
  const next = info.nextTier
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: `[Fractera] DNS quota warning — ${info.current}/${info.limit} (${pct}%) on ${info.planTier}`,
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#0a0a0a">
        <div style="display:inline-block;background:#f59e0b;color:#fff;font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;padding:5px 12px;border-radius:20px;margin-bottom:14px">⚠ WARNING</div>
        <h2 style="margin:0 0 12px;font-size:22px;font-weight:700">DNS quota approaching the limit</h2>

        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          The Cloudflare zone <strong>fractera.ai</strong> is at
          <strong>${info.current} / ${info.limit}</strong> DNS records (${pct}%) on the
          <strong>${escapeHtml(info.planTier)}</strong> plan. Only <strong>${remaining} records remain</strong>
          before new deploys start failing with <code>Record quota exceeded</code>.
        </p>

        <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:10px;padding:14px 16px;margin:18px 0">
          <p style="margin:0 0 4px;font-size:11px;color:#92400e;text-transform:uppercase;letter-spacing:1px;font-weight:700">Recommended action</p>
          <p style="margin:0;color:#451a03;line-height:1.6;font-size:14px">
            ${next
              ? `Upgrade Cloudflare to <strong>${escapeHtml(next.name)}</strong> (limit ${next.limit} records, ${escapeHtml(next.monthly)}). Or free up records by deleting test/orphaned servers via the dashboard.`
              : 'Free up records by deleting test/orphaned servers via the dashboard.'}
          </p>
        </div>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">How to verify</p>
        <ol style="margin:0 0 20px;padding-left:20px;line-height:1.7;color:#1f2937;font-size:14px">
          <li>Open <a href="https://dash.cloudflare.com" style="color:#f59e0b;font-weight:600">Cloudflare dashboard</a> → zone <strong>fractera.ai</strong> → DNS → Records.</li>
          <li>The count shown at the top of the page should match this email's number.</li>
          <li>Records modified within the last 24 hours are usually the most recent test deploys.</li>
        </ol>

        <p style="margin:0;color:#666;font-size:13px;line-height:1.6">
          Automatic alert from the deploy pipeline. Bootstrap is still running for current deploys — but plan the upgrade before the count hits ${info.limit}.
        </p>
      </div>
    `,
  })
}

// Sent to admin when DNS records hit (or exceed) the plan limit. Deploys
// are blocked at this point — the bootstrap's first-step quota check
// aborts before reaching `/api/register*`, which would have returned
// `code:81045 Record quota exceeded` from Cloudflare and left the user
// with a half-done install.
export async function sendDnsQuotaCriticalEmail(to: string, info: DnsQuotaInfo & { blockedDomain?: string }) {
  const next = info.nextTier
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: `[Fractera] DNS quota EXHAUSTED — deploys are blocked (${info.current}/${info.limit} on ${info.planTier})`,
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#0a0a0a">
        <div style="display:inline-block;background:#dc2626;color:#fff;font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;padding:5px 12px;border-radius:20px;margin-bottom:14px">✕ CRITICAL</div>
        <h2 style="margin:0 0 12px;font-size:22px;font-weight:700;color:#b91c1c">DNS quota exhausted — deploys blocked</h2>

        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          The Cloudflare zone <strong>fractera.ai</strong> has reached its DNS record limit:
          <strong>${info.current} / ${info.limit}</strong> on the <strong>${escapeHtml(info.planTier)}</strong> plan.
          New deploys are being rejected by the bootstrap's first-step quota check and will
          return <code>Record quota exceeded</code> from Cloudflare if forced.
        </p>

        ${info.blockedDomain ? `
        <div style="background:#fef2f2;border:1px solid #fecaca;border-radius:10px;padding:14px 16px;margin:18px 0">
          <p style="margin:0 0 4px;font-size:11px;color:#991b1b;text-transform:uppercase;letter-spacing:1px;font-weight:700">Last blocked deploy</p>
          <p style="margin:0;color:#7f1d1d;line-height:1.6;font-size:13px;font-family:monospace">${escapeHtml(info.blockedDomain)}</p>
        </div>
        ` : ''}

        <div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:10px;padding:14px 16px;margin:18px 0">
          <p style="margin:0 0 4px;font-size:11px;color:#0369a1;text-transform:uppercase;letter-spacing:1px;font-weight:700">Required action</p>
          <ol style="margin:0;padding-left:20px;color:#0c4a6e;line-height:1.7;font-size:14px">
            <li>${next ? `<strong>Upgrade Cloudflare to ${escapeHtml(next.name)}</strong> (${next.limit} records, ${escapeHtml(next.monthly)}) — fastest unblock.` : 'No higher plan available — only manual cleanup remaining.'}</li>
            <li><strong>OR</strong> run cleanup: <code>POST /api/admin/cleanup-all?execute=true</code> (admin@fractera.ai only) to delete orphaned test DNS records.</li>
            <li><strong>OR</strong> manually delete records via Cloudflare dashboard → zone <strong>fractera.ai</strong> → DNS → Records.</li>
          </ol>
        </div>

        <p style="margin:0;color:#666;font-size:13px;line-height:1.6">
          Until quota is freed, every <code>register_and_deploy</code> / <code>/api/install</code> / <code>/api/embed/install</code> / Light variant will fail at the first step. No user-facing damage — clear error returned, no partial server install.
        </p>
      </div>
    `,
  })
}

// ─── Fractera Main emails ──────────────────────────────────────────────────────

export async function sendMainInstallStartedEmail(to: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Fractera Main — your backend is being installed',
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:520px;margin:0 auto;padding:32px 24px;color:#111">
        <h2 style="margin:0 0 8px;font-size:22px;font-weight:700">Installation started</h2>
        <p style="margin:0 0 20px;color:#444;line-height:1.6">
          We're setting up <strong>Fractera</strong> on your server.
          This usually takes <strong>10–15 minutes</strong>.
        </p>
        <ul style="margin:0 0 20px;padding-left:20px;color:#444;line-height:2;font-size:14px">
          <li><strong>App</strong> — your landing page + protected dashboard</li>
          <li><strong>Auth</strong> — login, registration, roles, guest access</li>
          <li><strong>Admin</strong> — management panel (preview, DB, media, users)</li>
          <li><strong>Data</strong> — file &amp; media storage (SQLite + local storage)</li>
        </ul>
        <p style="margin:0;font-size:12px;color:#888;line-height:1.6">
          You can watch live progress at
          <a href="https://fractera.ai" style="color:#6366f1">fractera.ai</a>
          — the install bar on the page updates in real time.
        </p>
      </div>
    `,
  })
}

export async function sendMainWelcomeEmail(to: string, subdomain: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Your Fractera backend is live',
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;padding:32px 24px;color:#0a0a0a">
        <div style="text-align:center;padding-bottom:8px">
          <div style="display:inline-block;background:#10b981;color:#fff;font-size:11px;font-weight:600;letter-spacing:1.5px;text-transform:uppercase;padding:5px 12px;border-radius:20px;margin-bottom:14px">✓ Live</div>
          <h1 style="margin:0 0 8px;font-size:26px;font-weight:700;line-height:1.2">Your Fractera backend is live</h1>
          <p style="margin:0;color:#666;font-size:15px;line-height:1.5">Sign in to the admin panel to manage your site.</p>
        </div>
        <div style="text-align:center;margin:28px 0">
          <a href="https://${subdomain}/admin" style="display:inline-block;background:#6366f1;color:#fff;font-weight:600;font-size:15px;text-decoration:none;padding:14px 28px;border-radius:10px">Open admin panel →</a>
          <p style="margin:10px 0 0;font-size:12px;color:#888;font-family:monospace">${subdomain}/admin</p>
        </div>
        <table role="presentation" style="width:100%;border-collapse:separate;border-spacing:0 8px;margin:24px 0 0">
          <tr>
            <td style="background:#fafafa;border:1px solid #eee;border-radius:10px;padding:14px 16px">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:2px">Your public site</div>
              <a href="https://${subdomain}" style="color:#6366f1;font-weight:600;font-size:14px;text-decoration:none">https://${subdomain}</a>
            </td>
          </tr>
          <tr>
            <td style="background:#fafafa;border:1px solid #eee;border-radius:10px;padding:14px 16px">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:2px">Admin panel</div>
              <a href="https://${subdomain}/admin" style="color:#6366f1;font-weight:600;font-size:14px;text-decoration:none">https://${subdomain}/admin</a>
            </td>
          </tr>
        </table>
      </div>
    `,
  })
}

export async function sendMainRecoveryTokenEmail(to: string, serverToken: string) {
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Save your Fractera recovery token (backup — only if needed)',
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#0a0a0a">
        <h2 style="margin:0 0 12px;font-size:22px;font-weight:700">Save this in case anything goes wrong</h2>
        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          We just launched the deployment of your Fractera backend. <strong>You do not need to do anything right now.</strong>
        </p>
        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Your recovery token</p>
        <p style="margin:0 0 20px;font-size:13px;color:#0a0a0a;font-family:monospace;background:#f5f3ff;border:1px solid #c4b5fd;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all;user-select:all">${escapeHtml(serverToken)}</p>
        <p style="margin:0 0 16px;color:#555;font-size:13px;line-height:1.6;background:#fffbeb;border:1px solid #fef3c7;border-radius:8px;padding:12px">
          <strong style="color:#92400e">If everything goes well — you can safely ignore this email.</strong>
        </p>
        <p style="margin:0;color:#666;font-size:13px;line-height:1.6">Questions? Reply directly to this email — it goes to admin@fractera.ai.</p>
      </div>
    `,
  })
}

export async function sendMainDeployFailedEmail(to: string, errorMessage?: string, serverToken?: string) {
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Your Fractera deployment did not complete',
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:520px;margin:0 auto;padding:24px;color:#0a0a0a">
        <h2 style="margin:0 0 12px;font-size:22px;font-weight:700">Deployment did not complete</h2>
        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          We started setting up your Fractera backend, but the deployment ran into a problem.
        </p>
        ${errorMessage ? `
        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">What went wrong</p>
        <p style="margin:0 0 20px;font-size:13px;color:#b91c1c;font-family:monospace;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:12px;line-height:1.5;word-break:break-word">${escapeHtml(errorMessage)}</p>
        ` : ''}
        ${serverToken ? `
        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Your server token (for retry)</p>
        <p style="margin:0 0 20px;font-size:13px;color:#0a0a0a;font-family:monospace;background:#f5f3ff;border:1px solid #c4b5fd;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all">${escapeHtml(serverToken)}</p>
        ` : ''}
        <p style="margin:0;color:#666;font-size:13px;line-height:1.6">Need help? Reply to this email — it goes to admin@fractera.ai.</p>
      </div>
    `,
  })
}
