import { Resend } from 'resend'
import { LEGAL, legalAddressOneLine } from '@/config/legal'
import { buildUrls } from '@/lib/subdomain-helpers'

const resend = new Resend(process.env.RESEND_API_KEY)
const FROM = process.env.AUTH_RESEND_FROM ?? 'noreply@fractera.ai'

// CAN-SPAM Act (US) and analogous EU rules require a physical postal
// address in every commercial / transactional email. We append it
// automatically to whatever each template generated by wrapping the
// resend.emails.send() call — see sendEmail() below. Templates above
// continue to write their own HTML without thinking about the footer.
const CAN_SPAM_FOOTER_HTML = `
  <div style="margin-top:24px;padding-top:12px;border-top:1px solid #eee;font-size:11px;color:#999;line-height:1.5;font-family:sans-serif;text-align:center">
    ${legalAddressOneLine()}<br/>
    <a href="https://www.fractera.ai" style="color:#999;text-decoration:none">www.fractera.ai</a>
    &middot;
    <a href="mailto:${LEGAL.emails.support}" style="color:#999;text-decoration:none">${LEGAL.emails.support}</a>
  </div>
`

type SendArgs = Parameters<typeof resend.emails.send>[0]

async function sendEmail(args: SendArgs) {
  // Inject CAN-SPAM footer just before the LAST </div> in the HTML body.
  // If a template doesn't end in </div> (e.g. text-only or future plain),
  // append at the end. Either way, every outgoing email carries our
  // postal address + contact link.
  if (typeof args.html === 'string' && args.html.includes('</div>')) {
    const lastIdx = args.html.lastIndexOf('</div>')
    args = {
      ...args,
      html: args.html.slice(0, lastIdx) + CAN_SPAM_FOOTER_HTML + args.html.slice(lastIdx),
    }
  } else if (typeof args.html === 'string') {
    args = { ...args, html: args.html + CAN_SPAM_FOOTER_HTML }
  }
  return resend.emails.send(args)
}

const PIPELINE_SERVICES = [
  { name: 'Shell',  description: 'Your main application',       portHint: 'fractera-app' },
  { name: 'Auth',   description: 'Login & user management',     portHint: 'fractera-auth' },
  { name: 'Admin',  description: 'AI coding workspace',         portHint: 'fractera-admin' },
  { name: 'Bridge', description: 'AI platform terminals (×5)', portHint: 'fractera-bridge' },
  { name: 'Data',   description: 'File & media storage',        portHint: 'fractera-data' },
]

const AI_PLATFORMS = [
  'Claude Code',
  'Codex',
  'Gemini CLI',
  'Qwen Code',
  'Kimi Code',
]

function serviceListHtml(services: typeof PIPELINE_SERVICES) {
  return services
    .map(s => `<li style="margin:4px 0"><strong>${s.name}</strong> — ${s.description} <span style="color:#888;font-size:11px">(${s.portHint})</span></li>`)
    .join('\n')
}

export async function sendServerProvisionedEmail(to: string, ip: string, password: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Your Fractera server is created — IP and access details',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px">
        <h2 style="margin:0 0 12px">Your server is ready</h2>
        <p style="margin:0 0 16px">Your dedicated VPS has been created. Fractera is now being installed automatically — you'll receive a second email with your workspace URL when it's done (~15 min).</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Server credentials</p>
        <table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:24px">
          <tr><td style="padding:6px 0;color:#666;width:100px">IP address</td><td style="padding:6px 8px;font-weight:600">${ip}</td></tr>
          <tr><td style="padding:6px 0;color:#666">User</td><td style="padding:6px 8px;font-weight:600">root</td></tr>
          <tr><td style="padding:6px 0;color:#666">Password</td><td style="padding:6px 8px;font-weight:600;font-family:monospace">${password}</td></tr>
        </table>

        <p style="margin:0 0 8px;font-size:13px;color:#666">SSH access: <code style="background:#f4f4f4;padding:2px 6px;border-radius:3px">ssh root@${ip}</code></p>
        <p style="margin:0;font-size:12px;color:#999">You can use these credentials to upgrade your server plan directly on Contabo if needed.</p>
      </div>
    `,
  })
}

export async function sendWelcomeEmail(
  to: string,
  subdomain: string,
  credentials?: { ip: string; password: string }
) {
  // IP-mode deploy: subdomain stored as "ip-<IP>" — switch to HTTP IP:port links.
  const isIpMode = subdomain.startsWith('ip-')
  const ip = isIpMode ? subdomain.slice(3) : null
  const appUrl    = isIpMode ? `http://${ip}:3000` : `https://${subdomain}`
  const adminUrl  = isIpMode ? `http://${ip}:3002` : `https://admin.${subdomain}`
  const hermesUrl = isIpMode ? `http://${ip}:9119` : `https://hermes.${subdomain}`
  const brainUrl  = isIpMode ? `http://${ip}:9621` : `https://lightrag.${subdomain}`

  await sendEmail({
    from: FROM,
    to,
    subject: 'Your Fractera server is ready',
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;padding:32px 24px;color:#0a0a0a">

        <!-- Hero -->
        <div style="text-align:center;padding-bottom:8px">
          <div style="display:inline-block;background:#10b981;color:#fff;font-size:11px;font-weight:600;letter-spacing:1.5px;text-transform:uppercase;padding:5px 12px;border-radius:20px;margin-bottom:14px">✓ Live</div>
          <h1 style="margin:0 0 8px;font-size:26px;font-weight:700;line-height:1.2">Your Fractera server is live</h1>
          <p style="margin:0;color:#666;font-size:15px;line-height:1.5">Open your workspace below to start coding with AI.</p>
        </div>

        ${isIpMode ? `
        <!-- Autonomy note (IP-mode) -->
        <div style="margin:16px 0 0;padding:16px 18px;background:#ecfdf5;border:1px solid #10b981;border-radius:10px">
          <p style="margin:0 0 6px;font-size:13px;font-weight:700;color:#065f46">✓ Fully autonomous — zero dependency on Fractera</p>
          <p style="margin:0;color:#047857;font-size:13px;line-height:1.6">
            Your server runs entirely on your own VPS. No DNS, no domain through Fractera.
            If Fractera disappears tomorrow, your server keeps running. All code, data, and
            credentials are yours alone.
          </p>
        </div>
        ` : ''}

        <!-- Primary CTA -->
        <div style="text-align:center;margin:28px 0">
          <a href="${adminUrl}" style="display:inline-block;background:#6c47ff;color:#fff;font-weight:600;font-size:15px;text-decoration:none;padding:14px 28px;border-radius:10px">Open my workspace →</a>
          <p style="margin:10px 0 0;font-size:12px;color:#888;font-family:monospace">${adminUrl}</p>
        </div>

        <!-- The 3 main destinations -->
        <table role="presentation" style="width:100%;border-collapse:separate;border-spacing:0 8px;margin:24px 0 0">
          <tr>
            <td style="background:#fafafa;border:1px solid #eee;border-radius:10px;padding:14px 16px">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:2px">Live app</div>
              <a href="${appUrl}" style="color:#6c47ff;font-weight:600;font-size:14px;text-decoration:none;word-break:break-all">${appUrl}</a>
              <div style="font-size:12px;color:#888;margin-top:4px">The site you publish for your end users.</div>
            </td>
          </tr>
          <tr>
            <td style="background:#fafafa;border:1px solid #eee;border-radius:10px;padding:14px 16px">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:2px">Brain — Hermes Agent</div>
              <a href="${hermesUrl}" style="color:#6c47ff;font-weight:600;font-size:14px;text-decoration:none;word-break:break-all">${hermesUrl}</a>
              <div style="font-size:12px;color:#888;margin-top:4px">The thinking centre of your workspace. Delegates work across all connected AI subscriptions and runs autonomous tasks.</div>
            </td>
          </tr>
          <tr>
            <td style="background:#fafafa;border:1px solid #eee;border-radius:10px;padding:14px 16px">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:2px">Memory — LightRAG</div>
              <a href="${brainUrl}" style="color:#6c47ff;font-weight:600;font-size:14px;text-decoration:none;word-break:break-all">${brainUrl}</a>
              <div style="font-size:12px;color:#888;margin-top:4px">Long-term knowledge base. Feed it your docs and history — Brain queries it to stay grounded in your context.</div>
            </td>
          </tr>
        </table>

        <!-- Next steps — getting the most out of the workspace -->
        <div style="margin:32px 0 8px">
          <p style="margin:0 0 12px;font-size:11px;color:#999;text-transform:uppercase;letter-spacing:1px;font-weight:600">Recommended next steps</p>

          <table role="presentation" style="width:100%;border-collapse:separate;border-spacing:0 6px">
            <tr>
              <td style="padding:10px 14px;background:#fafafa;border-left:3px solid #6c47ff;border-radius:4px">
                <div style="font-size:13px;font-weight:600;color:#0a0a0a;margin-bottom:2px">1 · Get an OpenAI API key</div>
                <div style="font-size:12px;color:#555;line-height:1.5">
                  Needed to activate <strong>Memory</strong> (and as a fallback for <strong>Brain</strong>). Tokens are spent very economically — the embedding model used is among the cheapest available. Paste the key in <strong>Admin → Memory → settings</strong>.
                </div>
              </td>
            </tr>
            <tr>
              <td style="padding:10px 14px;background:#fafafa;border-left:3px solid #6c47ff;border-radius:4px">
                <div style="font-size:13px;font-weight:600;color:#0a0a0a;margin-bottom:2px">2 · Subscribe to OpenAI Codex <span style="color:#10b981;font-size:11px">recommended</span></div>
                <div style="font-size:12px;color:#555;line-height:1.5">
                  A flat-rate Codex subscription costs dramatically less than the equivalent API usage for the same workload. You <em>can</em> use an API key instead, but at heavy use the bill grows fast.
                </div>
              </td>
            </tr>
            <tr>
              <td style="padding:10px 14px;background:#fafafa;border-left:3px solid #6c47ff;border-radius:4px">
                <div style="font-size:13px;font-weight:600;color:#0a0a0a;margin-bottom:2px">3 · Prepare Telegram for hands-free access</div>
                <div style="font-size:12px;color:#555;line-height:1.5">
                  Talk to your <strong>Brain</strong> from your phone. Open Telegram, message <a href="https://t.me/BotFather" style="color:#6c47ff;text-decoration:none">@BotFather</a>, send <code style="background:#eee;padding:1px 4px;border-radius:3px;font-family:monospace">/newbot</code>, choose a name — BotFather replies with a token like <code style="background:#eee;padding:1px 4px;border-radius:3px;font-family:monospace">1234567:ABC…</code>. Paste it in <strong>Admin → Brain settings → Telegram bot token</strong>.
                </div>
              </td>
            </tr>
            <tr>
              <td style="padding:10px 14px;background:#fafafa;border-left:3px solid #6c47ff;border-radius:4px">
                <div style="font-size:13px;font-weight:600;color:#0a0a0a;margin-bottom:2px">4 · Buy a domain and connect it</div>
                <div style="font-size:12px;color:#555;line-height:1.5">
                  A real domain gives you HTTPS automatically and removes the browser security warnings. Buy one from any registrar (Namecheap, Porkbun, GoDaddy, etc.) and attach it in <strong>Admin → Personal Domain</strong>. We recommend using the registrar's own DNS panel rather than Cloudflare.
                </div>
                <div style="margin-top:8px;padding:8px 10px;background:#fffbeb;border:1px solid #fcd34d;border-radius:6px;font-size:11px;color:#92400e;line-height:1.5">
                  <strong>Don&rsquo;t buy an SSL certificate from your registrar.</strong> Registrars often up-sell SSL for $30&ndash;$80/year &mdash; you don&rsquo;t need it. Fractera issues a free Let&rsquo;s Encrypt certificate for you the moment you attach the domain, and renews it automatically every ~60 days. For restricted regions (e.g.&nbsp;Russia, Iran) or compliance-bound deployments where Let&rsquo;s Encrypt isn&rsquo;t available, you can upload your own certificate instead.
                </div>
              </td>
            </tr>
          </table>
        </div>

        <!-- Account note -->
        <div style="margin:24px 0 8px;padding:12px 14px;background:#f5f3ff;border-left:3px solid #6c47ff;border-radius:4px">
          <div style="font-size:13px;color:#444;line-height:1.5">
            Manage all your servers at <a href="https://www.fractera.ai/dashboard" style="color:#6c47ff;font-weight:600;text-decoration:none">fractera.ai/dashboard</a> — sign in with <strong>${to}</strong>.
          </div>
        </div>

        <!-- Sponsor CTA -->
        <div style="margin:32px 0 0;padding:18px 20px;background:linear-gradient(135deg,#faf5ff,#f5f3ff);border:1px solid #ddd6fe;border-radius:10px">
          <p style="margin:0 0 6px;font-size:14px;font-weight:700;color:#0a0a0a">Become a Fractera sponsor — from $1/mo</p>
          <p style="margin:0 0 12px;font-size:13px;color:#444;line-height:1.6">
            Sponsors get access to a private community where the Fractera team shares architecture details, helps debug, and ships fixes faster. Even $1/month makes a real difference and unlocks the private support channel.
          </p>
          <a href="https://www.fractera.ai/#sponsors" style="display:inline-block;background:#6c47ff;color:#fff;font-weight:600;font-size:13px;text-decoration:none;padding:10px 18px;border-radius:8px">View sponsor tiers →</a>
        </div>

        <!-- OR divider -->
        <div style="margin:24px 0;display:flex;align-items:center;text-align:center">
          <div style="flex:1;height:1px;background:#e5e5e5"></div>
          <span style="padding:0 14px;font-size:11px;color:#999;letter-spacing:2px;font-weight:600">OR</span>
          <div style="flex:1;height:1px;background:#e5e5e5"></div>
        </div>

        <!-- GitHub star CTA -->
        <div style="margin:0;padding:18px 20px;background:#fafafa;border:1px solid #eee;border-radius:10px;text-align:center">
          <p style="margin:0 0 6px;font-size:14px;font-weight:700;color:#0a0a0a">⭐ Star us on GitHub</p>
          <p style="margin:0 0 12px;font-size:13px;color:#444;line-height:1.6">
            A star takes one click and helps Fractera enormously — every star raises the project on search, makes it visible to other developers, and brings more contributors who improve the platform for everyone.
          </p>
          <a href="https://github.com/Fractera/ai-workspace" style="display:inline-block;background:#0a0a0a;color:#fff;font-weight:600;font-size:13px;text-decoration:none;padding:10px 18px;border-radius:8px">⭐ Star Fractera on GitHub</a>
        </div>

        ${credentials ? `
        <!-- SSH — collapsed-looking, deprioritized -->
        <div style="margin-top:32px;padding-top:20px;border-top:1px solid #eee">
          <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;font-weight:600;margin-bottom:8px">Server access (advanced)</div>
          <p style="margin:0 0 10px;font-size:12px;color:#666;line-height:1.5">For terminal access to the underlying VPS — install extra software, integrate third-party services, etc. Treat this like a password to your computer.</p>
          <table style="width:100%;border-collapse:collapse;font-size:13px;background:#fafafa;border:1px solid #eee;border-radius:8px;padding:0">
            <tr><td style="padding:8px 12px;color:#888;width:80px;border-bottom:1px solid #f0f0f0">IP</td><td style="padding:8px 12px;font-family:monospace;border-bottom:1px solid #f0f0f0">${credentials.ip}</td></tr>
            <tr><td style="padding:8px 12px;color:#888;border-bottom:1px solid #f0f0f0">User</td><td style="padding:8px 12px;font-family:monospace;border-bottom:1px solid #f0f0f0">root</td></tr>
            <tr><td style="padding:8px 12px;color:#888">Password</td><td style="padding:8px 12px;font-family:monospace">${credentials.password}</td></tr>
          </table>
        </div>
        ` : ''}

        ${isIpMode ? `
        <!-- How to open: incognito + bypass warning (moved to bottom, just above footer) -->
        <div style="margin:24px 0 0;padding:14px 18px;background:#fffbeb;border:1px solid #fcd34d;border-radius:10px">
          <p style="margin:0 0 8px;font-size:13px;font-weight:700;color:#92400e">⚠ How to open the links above — please read</p>
          <p style="margin:0 0 10px;color:#92400e;font-size:13px;line-height:1.6">
            These links use plain HTTP (your server has no SSL certificate yet — that's normal until you
            attach your own domain). Your browser will show <strong>"Not secure"</strong> or block the
            page. Follow these steps to open it safely:
          </p>
          <ol style="margin:0 0 10px;padding-left:22px;color:#92400e;font-size:13px;line-height:1.9">
            <li>Open the link in an <strong>incognito / private window</strong>
              (Chrome: <code style="background:#fef3c7;padding:1px 6px;border-radius:3px;font-family:monospace">Ctrl+Shift+N</code>,
              Firefox: <code style="background:#fef3c7;padding:1px 6px;border-radius:3px;font-family:monospace">Ctrl+Shift+P</code>).
              This avoids cached HTTPS redirects from any previous server.</li>
            <li>If you still see a security warning, click <strong>"Advanced"</strong> → <strong>"Proceed to ${ip} (unsafe)"</strong>.
              In Chrome, you can also type <code style="background:#fef3c7;padding:1px 6px;border-radius:3px;font-family:monospace">thisisunsafe</code>
              directly on the warning page to bypass.</li>
            <li>You are connecting to <strong>your own server</strong> — no third party is intercepting your traffic.
              The warning only means "no SSL certificate", not "untrusted website".</li>
          </ol>
          <p style="margin:0;padding-top:8px;border-top:1px solid #fde68a;color:#78350f;font-size:13px;line-height:1.6">
            <strong>✓ The warning disappears automatically</strong> once you attach a real domain in the
            admin panel — Fractera will obtain a free Let's Encrypt SSL certificate for you, and the green
            padlock will appear in your browser.
          </p>
        </div>
        ` : ''}

        <!-- AI platforms — minor footnote -->
        <p style="margin:24px 0 0;font-size:11px;color:#aaa;text-align:center;line-height:1.6">
          Powered by ${AI_PLATFORMS.join(' · ')}
        </p>

      </div>
    `,
  })
}

export async function sendExpiryWarningEmail(to: string, daysLeft: number, subdomain: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: `Your Fractera subscription expires in ${daysLeft} days`,
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px">
        <h2 style="margin:0 0 12px">Subscription expiring soon</h2>
        <p style="margin:0 0 16px">Your Fractera server <strong>${subdomain}</strong> subscription expires in <strong>${daysLeft} day${daysLeft === 1 ? '' : 's'}</strong>.</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Services at risk (5 pipeline services)</p>
        <ul style="margin:0 0 16px;padding-left:20px;line-height:1.8">
          ${serviceListHtml(PIPELINE_SERVICES)}
        </ul>

        <p style="margin:0 0 16px">To keep all services running, please renew your subscription before the expiry date.</p>
        <p><a href="https://fractera.ai">Manage subscription →</a></p>
      </div>
    `,
  })
}


export async function sendQueuedEmail(to: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Fractera — your workspace is being prepared',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px">
        <h2 style="margin:0 0 12px">Purchase confirmed</h2>
        <p style="margin:0 0 16px">Thank you! Your Fractera workspace is being prepared. You will receive a second email with your server IP, login, and password within <strong>60 minutes</strong>.</p>
        <p style="margin:0;font-size:12px;color:#999">If you have any questions, reply to this email.</p>
      </div>
    `,
  })
}

export async function sendAdminAlertEmail(userEmail: string, subscriptionId: string) {
  const adminUrl = process.env.AUTH_URL ?? process.env.NEXTAUTH_URL ?? 'https://fractera.ai'
  await sendEmail({
    from: FROM,
    to: 'admin@fractera.ai',
    subject: '🚨 Fractera — user purchased with empty pool',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px">
        <h2 style="margin:0 0 12px;color:#e53e3e">Action required: no servers in pool</h2>
        <p style="margin:0 0 16px">A user completed payment but no server was available in the reserve pool.</p>
        <table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:24px">
          <tr><td style="padding:6px 0;color:#666;width:140px">User email</td><td style="padding:6px 8px;font-weight:600">${userEmail}</td></tr>
          <tr><td style="padding:6px 0;color:#666">Subscription ID</td><td style="padding:6px 8px;font-family:monospace;font-size:12px">${subscriptionId}</td></tr>
        </table>
        <p style="margin:0 0 16px">Add a server to the pool and assign it to this user:</p>
        <a href="${adminUrl}/admin" style="display:inline-block;background:#fff;color:#000;padding:10px 20px;border-radius:8px;text-decoration:none;font-weight:600">Open Admin Panel →</a>
      </div>
    `,
  })
}


export async function sendInstallStartedEmail(to: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Your Fractera installation has started',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px;color:#111">
        <h2 style="margin:0 0 8px;font-size:22px;font-weight:700">Installation started</h2>
        <p style="margin:0 0 20px;color:#444;line-height:1.6">
          We're setting up Fractera on your server right now.
          This usually takes <strong>15–20 minutes</strong>.
        </p>

        <p style="margin:0 0 6px;font-size:11px;color:#999;text-transform:uppercase;letter-spacing:1px">What happens next</p>
        <ol style="margin:0 0 20px;padding-left:20px;color:#444;line-height:2">
          <li>You'll receive a short update when dependencies are installed</li>
          <li>The final email will contain your workspace URLs and SSH credentials</li>
        </ol>

        <div style="background:#f7f7f7;border-radius:8px;padding:16px;margin-bottom:20px">
          <p style="margin:0 0 8px;font-size:13px;font-weight:600;color:#333">You can also check status anytime</p>
          <p style="margin:0;font-size:13px;color:#555;line-height:1.6">
            Visit <a href="https://fractera.ai" style="color:#6c47ff">fractera.ai</a>, sign in, and open the
            <strong>Servers</strong> tab — your domain will appear there once installation is complete.
          </p>
        </div>

        <p style="margin:0;font-size:12px;color:#888;line-height:1.6">
          If you re-enter your server IP and password on fractera.ai, the dashboard will detect the current state
          and offer options like removing Fractera branding or deleting the server.
        </p>
      </div>
    `,
  })
}



export async function sendInstallProgressEmail(to: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Fractera: dependencies installed — building services',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px;color:#111">
        <h2 style="margin:0 0 8px;font-size:22px;font-weight:700">Good progress</h2>
        <p style="margin:0 0 20px;color:#444;line-height:1.6">
          All dependencies have been installed on your server.
          We're now building the Fractera services and configuring your domain.
        </p>
        <p style="margin:0 0 20px;color:#444;line-height:1.6">
          You'll receive the final email with your workspace URLs in <strong>5–10 more minutes</strong>.
        </p>
        <p style="margin:0;font-size:12px;color:#888">
          Check status anytime at <a href="https://fractera.ai" style="color:#6c47ff">fractera.ai</a> → Servers tab.
        </p>
      </div>
    `,
  })
}

export async function sendSponsorThankYouEmail(to: string, tier: 's1' | 's5' | 's20') {
  const tierLabel = tier === 's1' ? '$1/month' : tier === 's5' ? '$5/month' : '$20/month'
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Thank you for sponsoring Fractera 💛',
    html: `
      <div style="font-family:sans-serif;max-width:560px;margin:0 auto;padding:32px 24px;color:#111">
        <div style="text-align:center;font-size:56px;line-height:1;margin-bottom:16px">💛</div>
        <h1 style="margin:0 0 16px;font-size:26px;font-weight:700;text-align:center;color:#111">
          Thank you for becoming a sponsor!
        </h1>

        <p style="margin:0 0 20px;color:#333;line-height:1.7;font-size:16px;text-align:center">
          Your <strong>${tierLabel}</strong> support means the world to me — Fractera is built by one person, and every sponsor is a real boost.
        </p>

        <div style="background:linear-gradient(135deg,#fef9c3 0%,#fef3c7 100%);border:1px solid #fcd34d;border-radius:14px;padding:20px;margin:24px 0">
          <p style="margin:0 0 8px;font-size:11px;color:#92400e;text-transform:uppercase;letter-spacing:1.5px;font-weight:700">What happens next</p>
          <ul style="margin:0;padding-left:18px;color:#1f2937;line-height:1.8;font-size:14px">
            <li>Your email will be listed on the <strong>Sponsors</strong> page here on fractera.ai</li>
            <li>You'll be added to the public Sponsors section in our GitHub repository</li>
            <li>You can manage or cancel your subscription anytime from the Dashboard</li>
          </ul>
        </div>

        <div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:14px;padding:20px;margin:24px 0;text-align:center">
          <p style="margin:0 0 8px;font-size:11px;color:#1e40af;text-transform:uppercase;letter-spacing:1.5px;font-weight:700">Join the private Telegram group</p>
          <p style="margin:0 0 14px;color:#1e3a8a;line-height:1.6;font-size:14px">
            A closed group for Fractera sponsors — roadmap previews, early features, and direct chat with the team.
          </p>
          <a href="https://t.me/+7TABWdWliKBiYmI8" style="display:inline-block;background:#2563eb;color:#fff;padding:10px 22px;border-radius:10px;text-decoration:none;font-weight:600;font-size:14px">
            Join Telegram →
          </a>
        </div>

        <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:14px;padding:20px;margin:24px 0">
          <p style="margin:0 0 8px;font-size:11px;color:#374151;text-transform:uppercase;letter-spacing:1.5px;font-weight:700">We're in touch</p>
          <p style="margin:0;color:#374151;line-height:1.7;font-size:14px">
            If you have ideas, feature requests, or wishes for the project —
            <strong>just reply to this email</strong>. Your message lands directly with me, and I read every one personally.
          </p>
        </div>

        <p style="margin:32px 0 0;color:#6b7280;line-height:1.6;font-size:13px;text-align:center">
          With sincere gratitude,<br>
          <strong style="color:#111">The Fractera team</strong>
        </p>
      </div>
    `,
  })
}

export async function sendCancellationEmail(to: string) {
  await sendEmail({
    from: FROM,
    to,
    subject: 'Fractera subscription cancelled',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px">
        <h2 style="margin:0 0 12px">Subscription cancelled</h2>
        <p style="margin:0 0 16px">Your Fractera subscription has been cancelled. The following pipeline services will be deactivated at the end of the current billing period:</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Services being deactivated (5 pipeline services)</p>
        <ul style="margin:0 0 16px;padding-left:20px;line-height:1.8">
          ${serviceListHtml(PIPELINE_SERVICES)}
        </ul>

        <p style="margin:0 0 16px">If this was a mistake, you can resubscribe at any time from <a href="https://fractera.ai">fractera.ai</a>.</p>
      </div>
    `,
  })
}

export async function sendPartnerWelcomeEmail(to: string, slug: string) {
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Your Fractera Partner cabinet is active',
    html: `
      <div style="font-family:sans-serif;max-width:560px;margin:0 auto;padding:32px 24px;color:#111">
        <h1 style="margin:0 0 16px;font-size:24px;font-weight:700;color:#111">
          Welcome to the Fractera Partner Program
        </h1>

        <p style="margin:0 0 20px;color:#333;line-height:1.7;font-size:15px">
          Your partner cabinet is now active. Below is your personal partner identifier — keep it safe; you will use it when configuring your affiliate links and (later) when configuring the embeddable widget and MCP activation.
        </p>

        <div style="background:linear-gradient(135deg,#f3f0ff 0%,#ede4ff 100%);border:1px solid #c4b5fd;border-radius:14px;padding:20px;margin:24px 0">
          <p style="margin:0 0 8px;font-size:11px;color:#6d28d9;text-transform:uppercase;letter-spacing:1.5px;font-weight:700">Your partner ID</p>
          <p style="margin:0;font-family:monospace;font-size:20px;font-weight:700;color:#1f2937;letter-spacing:0.5px">${slug}</p>
        </div>

        <h2 style="margin:24px 0 12px;font-size:18px;font-weight:700;color:#111">Widget snippet</h2>
        <p style="margin:0 0 16px;color:#333;line-height:1.7;font-size:14px">
          The embeddable signup widget is under active development. Once it ships, you will be able to copy a ready-to-paste snippet from your partner cabinet at <a href="https://fractera.ai" style="color:#6c47ff;font-weight:600">fractera.ai</a> → Dashboard → Partner cabinet. The snippet will look approximately like this:
        </p>

        <pre style="background:#0b0b0d;color:#a7f3d0;font-family:monospace;font-size:12px;border-radius:10px;padding:16px;overflow:auto;line-height:1.5;margin:0 0 16px"><code>&lt;iframe
  src="https://embed.fractera.ai/signup?ref=${slug}"
  width="100%" height="640"
  style="border:0; border-radius:16px"
&gt;&lt;/iframe&gt;</code></pre>

        <p style="margin:0 0 24px;color:#666;line-height:1.6;font-size:13px">
          The widget will surface a call-to-action button labelled with your hosting provider name and linking to your affiliate URL — both you configure in the cabinet once it ships.
        </p>

        <h2 style="margin:24px 0 12px;font-size:18px;font-weight:700;color:#111">What to do next</h2>
        <ul style="margin:0 0 16px;padding-left:20px;line-height:1.8;color:#1f2937;font-size:14px">
          <li>Open <a href="https://fractera.ai" style="color:#6c47ff;font-weight:600">fractera.ai</a> → Dashboard (top-right corner of the page after signing in) → tab <strong>«Partner cabinet»</strong>.</li>
          <li>Apply for an affiliate program with any VPS provider you want to recommend (Contabo's program is documented at <a href="https://contabo.com/en/affiliate-program/" style="color:#6c47ff;font-weight:600">contabo.com/en/affiliate-program/</a> — but any host with an affiliate program works).</li>
          <li>Once approved by the provider, connect your affiliate link in the cabinet — that will happen as soon as link management ships (next development step).</li>
        </ul>

        <p style="margin:24px 0 0;color:#666;font-size:13px;line-height:1.6">
          Questions? Reply directly to this email — it goes to admin@fractera.ai.
        </p>
      </div>
    `,
  })
}

// Sent right after a ServerToken is created — by ANY deploy path (main /api/install,
// embed /api/embed/install, or MCP register_and_deploy). The install-started email
// is sent BEFORE the ServerToken row exists, so it cannot carry the recovery token —
// this follow-up closes that gap. The token unlocks MCP retry_deploy if anything
// breaks later. Best-effort: callers wrap in try/catch and never fail the deploy
// because of an email send error.
export async function sendRecoveryTokenEmail(to: string, serverToken: string) {
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Save your Fractera recovery token (backup — only if needed)',
    html: `
      <div style="font-family:sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#111">
        <h2 style="margin:0 0 12px">Save this in case anything goes wrong</h2>

        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          We just launched the deployment of your Fractera server. The next
          email you receive will either contain your live URL (most likely) or
          a failure report. <strong>You do not need to do anything right now.</strong>
        </p>

        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          This message is a backup. If the deploy ever gets stuck, fails, or
          you want to re-run it later, the token below lets any AI agent
          (Claude, ChatGPT/Codex, Gemini) recover the same server for you.
        </p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Your recovery token</p>
        <p style="margin:0 0 20px;font-size:13px;color:#1f2937;font-family:monospace;background:#f5f3ff;border:1px solid #ddd6fe;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all;user-select:all">${escapeHtml(serverToken)}</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Fractera MCP server URL</p>
        <p style="margin:0 0 20px;font-size:13px;color:#1f2937;font-family:monospace;background:#f5f3ff;border:1px solid #ddd6fe;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all;user-select:all">https://www.fractera.ai/api/mcp</p>

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">How to use it (only if you need to)</p>
        <ol style="margin:0 0 20px;padding-left:20px;line-height:1.7;color:#1f2937;font-size:14px">
          <li style="margin-bottom:8px">
            Open the AI agent you use day-to-day — Claude, ChatGPT/Codex, or
            Gemini. Some agents call this an &ldquo;MCP server&rdquo;, others
            call it a &ldquo;connector&rdquo; — same thing.
          </li>
          <li style="margin-bottom:8px">
            Tell the agent in plain language: <em>&ldquo;Please connect the
            MCP server at https://www.fractera.ai/api/mcp. Once connected, retry
            my Fractera deploy with this recovery token: ${escapeHtml(serverToken.slice(0, 12))}&hellip;&rdquo;</em>
            The agent will walk you through the 15-second connector
            setup inside its own interface, then call our <code>retry_deploy</code>
            tool with your token.
          </li>
          <li style="margin-bottom:8px">
            That&rsquo;s it. The agent will wipe the partial install and run a
            fresh deploy on the same server. You&rsquo;ll receive a new welcome
            email when it&rsquo;s done.
          </li>
        </ol>

        <p style="margin:0 0 16px;color:#555;font-size:13px;line-height:1.6;background:#fffbeb;border:1px solid #fef3c7;border-radius:8px;padding:12px">
          <strong style="color:#92400e">If everything goes well — you can safely
          ignore this email.</strong> Most deploys complete on the first try.
          We send this as a one-time safety net because the recovery token is
          generated by the deploy itself and is not available in the
          install-started email.
        </p>

        <p style="margin:0 0 16px;color:#777;font-size:12px;line-height:1.6">
          Treat the recovery token like a password — anyone who has it can
          re-run a deploy on this same server using your stored IP and
          credentials. Do not share it publicly.
        </p>

        <p style="margin:0;color:#666;font-size:13px;line-height:1.6">
          Questions? Reply directly to this email — it goes to admin@fractera.ai.
        </p>
      </div>
    `,
  })
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] ?? c))
}

type CompanyBrainInquiry = {
  email: string
  name?: string
  company?: string
  area?: string
  country?: string
  companyDoes?: string
  aiTask?: string
  telegram?: string
  lang?: string
}

export async function sendCompanyBrainInquiryEmail(inquiry: CompanyBrainInquiry) {
  const rows: [string, string | undefined][] = [
    ['Email', inquiry.email],
    ['Name', inquiry.name],
    ['Company', inquiry.company],
    ['Area of activity', inquiry.area],
    ['Country', inquiry.country],
    ['What the company does', inquiry.companyDoes],
    ['AI task they want to solve', inquiry.aiTask],
    ['Telegram', inquiry.telegram],
    ['UI language at submission', inquiry.lang],
  ]
  const rowsHtml = rows
    .filter(([, v]) => v && v.trim())
    .map(([label, v]) => `
      <tr>
        <td style="padding:8px 12px;font-size:12px;color:#666;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #eee;vertical-align:top;white-space:nowrap">${escapeHtml(label)}</td>
        <td style="padding:8px 12px;font-size:14px;color:#111;border-bottom:1px solid #eee;white-space:pre-wrap;line-height:1.5">${escapeHtml((v ?? '').trim())}</td>
      </tr>
    `).join('\n')

  await sendEmail({
    from: FROM,
    to: 'admin@fractera.ai',
    replyTo: inquiry.email,
    subject: `AI Company Brain inquiry — ${inquiry.company?.trim() || inquiry.email}`,
    html: `
      <div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#111">
        <h2 style="margin:0 0 6px">Fractera AI Company Brain — new consultation inquiry</h2>
        <p style="margin:0 0 16px;color:#666;font-size:13px">Reply directly to this email — it goes to the inquirer (${escapeHtml(inquiry.email)}).</p>
        <table style="width:100%;border-collapse:collapse;border:1px solid #eee">
          ${rowsHtml}
        </table>
      </div>
    `,
  })
}

export async function sendDeployFailedEmail(to: string, errorMessage?: string, serverToken?: string) {
  await sendEmail({
    from: FROM,
    to,
    replyTo: 'admin@fractera.ai',
    subject: 'Your Fractera deployment did not complete',
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px;color:#111">
        <h2 style="margin:0 0 12px">Deployment did not complete</h2>
        <p style="margin:0 0 16px;color:#333;line-height:1.6">
          We started setting up your Fractera server, but the deployment ran
          into a problem and could not finish. Your server is <strong>not
          ready</strong> — the URL we mentioned in the previous email will not
          work.
        </p>

        ${errorMessage ? `
        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">What went wrong</p>
        <p style="margin:0 0 20px;font-size:13px;color:#b91c1c;font-family:monospace;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:12px;line-height:1.5;word-break:break-word">${errorMessage}</p>
        ` : ''}

        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">How to recover</p>
        <ol style="margin:0 0 20px;padding-left:20px;line-height:1.8;color:#1f2937;font-size:14px">
          <li>
            Open your dashboard at
            <a href="https://fractera.ai" style="color:#6c47ff;font-weight:600">fractera.ai</a>
            (sign in with <strong>${to}</strong>) &rarr; <strong>Servers</strong>,
            delete the failed deployment, and start a new one from the home page.
          </li>
          <li>
            Or use the <strong>MCP-assisted recovery</strong>: paste the
            server_token below into an AI agent that has the
            <a href="https://fractera.ai/en/partners#mcp" style="color:#6c47ff;font-weight:600">Fractera MCP</a>
            enabled (Claude Code, Codex, Gemini CLI). The agent will call
            <code>retry_deploy</code> and finish the setup of the server you
            already started.
            <br/>
            <span style="display:inline-block;margin-top:6px;color:#d97706;font-size:12px">
              * Never used MCP? Copy this URL and ask your AI agent to connect it: <strong>https://www.fractera.ai/api/mcp</strong> — setup takes ~15 seconds.
            </span>
          </li>
        </ol>

        ${serverToken ? `
        <p style="margin:0 0 6px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px">Your server_token</p>
        <p style="margin:0 0 20px;font-size:13px;color:#1f2937;font-family:monospace;background:#f5f3ff;border:1px solid #ddd6fe;border-radius:8px;padding:12px;line-height:1.5;word-break:break-all;user-select:all">${serverToken}</p>
        ` : ''}

        <p style="margin:0;color:#666;font-size:13px;line-height:1.6">
          Need help? Reply directly to this email — it goes to admin@fractera.ai.
        </p>
      </div>
    `,
  })
}
