import { AUTHOR } from '@/lib/author'
import type { FrameworkMeta } from '../../_lib/post'

// Non-translatable fields for /framework/django. Standard co-located page: content lives
// in this folder's _data (en.ts + ru.ts), not generated by buildFrameworkData.
export const meta: FrameworkMeta = {
  slug: 'django',
  subPath: '/framework/django',
  order: 24,
  tags: ['Django', 'Python', 'Full-stack', 'ORM', 'Self-hosted', 'Agentic Engineering'],
  author: { name: AUTHOR.name, role: AUTHOR.role, url: AUTHOR.url },
  ogImage: '/Fractera-ai-workspace-screenshot.png',
}
